initial version of the mineflayer based npm test
OASIS-learn-study/minecraft-storeys-maker pull request #348
Opened 2022-04-09 16:54 UTC by edewit

```bash
$> cd test-utils/mineflayer
$> gradle test
```

This test will fail atm because the server isn't in offline mode
and the `Player` that mineflayer uses doesn't have rights to execute `/make`

Once these 2 things are fixed this test will pass

2022-04-11 18:27 UTC, vorburger requested changes

2022-04-11 18:27 UTC, vorburger commented on test-utils/mineflayer/settings.gradle
> +rootProject.name = 'mineflayer'
@edewit I'm pretty sure `settings.gradle` is supposed to only exist once in a monorepo kind of project like this one - do you want to remove this?

2022-04-11 18:27 UTC, vorburger commented on test-utils/mineflayer/storeys.test.js
> +    jest.useFakeTimers('legacy');
It's perhaps worth an inline comment (and/or link to respective `mineflayer` doc?) what this does?

2022-04-11 18:27 UTC, vorburger commented on test-utils/mineflayer/build.gradle
> +plugins {
@edewit why did you "nest" `mineflayer/` under `test-utils/`, which is a Java (!) testing utility library, containing (only!) the `ClasspathHellDuplicatesChecker`? I'm surprised that this even works with Gradle, given that there is also a `test-utils/build.gradle`. How about e.g. `git mv test-utils/mineflayer/ test-mineflayer/` ?

2022-04-11 18:40 UTC, vorburger commented
> This test will fail atm because the server isn't in offline mode

We COULD change `ENV SKIP_SERVER_PROPERTIES` from `true` to `false` in both `Dockerfile` and `Dockerfile-local` AND `ENV ONLINE_MODE=FALSE` BUT then we'll loose being in _creative,_ because of https://github.com/itzg/docker-minecraft-server/issues/1452. I can't quite think of a "workaround". Unless @edewit you can think of something, i think we have 2 obvious choice here: (a) switch it in our `server.properties` #L43 (in `minecraft-server/` NOT in `minecraft-server-test-data`), (b) wait for @itzg to release a new image. For me we can do (a) for now, and "later" revert and (b). Unless @itzg jump on this with this incredible support and wants to make a new release in the next few days?

> and the `Player` that mineflayer uses doesn't have rights to execute `/make`

I'm torn how to best go about this. It seems like a shame to give up on the permission check for `/make`. But even if we had  #276 for LuckPerms (I could priorititze working on that next), I don't know how we would "grant the anonymous Mineflyer user the permission to `/make`. Hm.

2022-04-11 23:31 UTC, itzg commented
I had gotten myself confused and thought I was caught up on releases 😃 There is now a new release with the changes: https://github.com/itzg/docker-minecraft-server/releases/tag/2022.6.0

2022-04-12 05:39 UTC, edewit commented on test-utils/mineflayer/build.gradle
> +plugins {
I don't know where you want to put this so I put it into test utils as it is a standalone util to test? But I'll move it to test-mineflayer no problm

2022-04-12 05:39 UTC, edewit commented on test-utils/mineflayer/storeys.test.js
> +    jest.useFakeTimers('legacy');
mineflayer does an import after the test is done and jest doesn't like it

2022-04-12 05:41 UTC, edewit commented
Wauw @itzg has our back, so we can do (b)

2022-04-13 18:14 UTC, vorburger commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
@edewit as-is, this actually fails the build (note e.g. how this PR is "red"), due to `Execution failed for task ':test-mineflayer:npmTest'`. I think to really make this work from Gradle, we would have to write a Java test that uses testcontainers to launch the container, and then exec `node storeys.test.js` (or whatever the right syntax is)... did you want to go that route? I think it may be easier to remove including 'test-mineflayer' here, and just doing `./gradlew test-mineflayer:npmTest` in the the `./test` script, WDYT?

2022-04-13 18:57 UTC, edewit commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
Right it needs to start the server with the test script first, we can do that in node as well it will be easy let me update this PR to execute the `./test` script before the tests start. What is still needed though are 2 things:

1. Make sure the "dummy" player is allowed to execute `/make`
1. Start the test server in offline mode

2022-04-13 19:00 UTC, edewit commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
The problem is that `/test` builds the project and then runs it and that now this mineflayer is also deepened on the test, so let me update it so that mineflayer doesn't execute by default

2022-04-13 19:01 UTC, vorburger commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
Yeah. For 1. I'm exploring if I can add LuckPerms (#276) so that we could have a user named `mineflayer` and give it permission to `/make`. For 2. check out #353 - once you merge that and rebase, you can remove my TODO in `test` and add `-e ONLINE_MODE=FALSE` in this PR.

2022-04-13 19:03 UTC, edewit commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
right done as you suggested

2022-04-24 19:01 UTC, vorburger commented on settings.gradle
> +include 'test-utils', 'engine', 'api', 'storeys', 'web', 'scratch3', 'test-mineflayer'
Thanks!

2022-04-24 19:01 UTC, vorburger approved these changes

2022-04-24 19:01 UTC, merged