made whenInside locations work
OASIS-learn-study/minecraft-storeys-maker pull request #426
Opened 2022-10-07 21:12 UTC by edewit

2022-10-07 21:54 UTC, vorburger requested changes
build fails

2022-10-09 08:56 UTC, vorburger requested changes

2022-10-09 08:56 UTC, vorburger commented on api-jvm-impl/src/main/java/ch/vorburger/minecraft/storeys/japi/impl/events/EventService.java
> +        }
@edewit how about something like else LOG.warn "Unknown Location: {}", name (with name factored out in a var above) here? Just thinking that this could help us what's going on if we ever face any issues with this feature.

2022-10-09 08:56 UTC, vorburger commented on docs/testing.md
> +1. _TODO explain how to create a when aside area, and how to name it; or link to a YouTube video about it_
@edewit do you want to edit this further?

2022-10-09 08:56 UTC, vorburger commented on docs/testing.md
> +1. _TODO Walk (where?) and make sure a "you jumped!" is shown as title
@edewit do you want to edit this further to clarify?

2022-10-09 08:56 UTC, vorburger commented on minecraft-server-test-data/config/storeys-web.conf
> +        player=fb79c1a9-72bd-34dc-9775-c2ac868d7ccf
So... this only triggers when YOU enter this area? Is this really what we want? I thought it would make more sense if it was always for all and any Player (only, but not other entities).

2022-10-09 08:56 UTC, vorburger commented on web/src/main/java/ch/vorburger/minecraft/storeys/web/LocationToolListener.java
> +    private EventContext eventContext;
```suggestion
    private final EventContext eventContext;
```

2022-10-09 08:56 UTC, vorburger commented on web/src/main/java/ch/vorburger/minecraft/storeys/web/LocationToolListener.java
> +    private PluginInstance plugin;
```suggestion
    private final PluginInstance plugin;
```

2022-10-09 08:56 UTC, vorburger commented on web/src/main/java/ch/vorburger/minecraft/storeys/web/LocationToolListener.java
> +    private PluginInstance plugin;
```suggestion
    private final PluginInstance plugin;
```

2022-10-09 09:04 UTC, vorburger commented on test-mineflayer/storeys.test.js
>          done();
This will have a merge conflict after #427 is merged (first)

2022-10-09 09:09 UTC, vorburger commented
blockly-command.cy.js.mp4 looks very cool, I watched it; but probably shouldn't be in git? Unless I misunderstood, is that to assert it like this? Or just a recording for debugging? Anyway we won't have that recording feature until #400, right? PS: Watching this recording reminded me of my https://github.com/vorburger/webdriver-reporting!

2022-10-10 05:25 UTC, edewit commented on docs/testing.md
> +1. _TODO explain how to create a when aside area, and how to name it; or link to a YouTube video about it_
Ahh yeah I can make a short video for it that would be cool

2022-10-10 05:36 UTC, edewit commented
> blockly-command.cy.js.mp4 looks very cool, I watched it; but probably shouldn't be in git? Unless I misunderstood, is that to assert it like this? Or just a recording for debugging? Anyway we won't have that recording feature until #400, right? PS: Watching this recording reminded me of my https://github.com/vorburger/webdriver-reporting!

Oops yes that shouldn't be in git. It's for debugging as the browser test is headless it's handy do have this video to see why a test failed.

2022-10-10 05:48 UTC, edewit commented on minecraft-server-test-data/config/storeys-web.conf
> +        player=fb79c1a9-72bd-34dc-9775-c2ac868d7ccf
No it triggers every time any player enters, `player` here is that it is mine, this makes names naming a bit better as the name is on a player basis. You can have a trigger called "box" as well.

2022-10-10 08:48 UTC, edewit commented on docs/testing.md
> +1. _TODO explain how to create a when aside area, and how to name it; or link to a YouTube video about it_
https://youtu.be/fMjQxQcm0qM

2022-11-04 18:24 UTC, vorburger approved these changes

2022-11-04 18:25 UTC, merged